export const SET_GROUP_ID = 'SET_GROUP_ID';

export const QUEUE_FETCH = 'QUEUE_FETCH';
export const QUEUE_FETCH_FULFILLED = 'QUEUE_FETCH_FULFILLED';

export const REMOVE_QUEUE_ITEM = 'REMOVE_QUEUE_ITEM';

export const POP_QUEUE_FETCH = 'POP_QUEUE_FETCH';
export const POP_QUEUE_FETCH_FULFILLED = 'POP_QUEUE_FETCH_FULFILLED';

export const YOUTUBE_FETCH = 'YOUTUBE_FETCH';
export const YOUTUBE_FETCH_FULFILLED = 'YOUTUBE_FETCH_FULFILLED';
