export const SET_GROUP_ID = 'SET_GROUP_ID';

export const QUEUE_FETCH = 'QUEUE_FETCH';
export const QUEUE_FETCH_FULFILLED = 'QUEUE_FETCH_FULFILLED';

export const YOUTUBE_FETCH = 'YOUTUBE_FETCH';
export const YOUTUBE_FETCH_FULFILLED = 'YOUTUBE_FETCH_FULFILLED';
